### ISSUE TITLE
Plans for an ed25519 crate based on this one?

### ISSUE THREAD

**Issue by coltfred** [zkcrypto/curve25519-dalek-ng#8]
Due to the rift that seems to have formed on the dalek-cryptography organization, what is the overall plan for the other crates that were in that org? I'm specifically interested in ed25519, but wondering if there are plans for more than just curve25519.

As a user this is all quite confusing, so I'm just trying to do my best to navigate the waters of this delicate situation.

**Comment by burdges** [comment]
[ed25519-zebra](https://github.com/ZcashFoundation/ed25519-zebra) handles single vs batch verification correctly, which ed25519-dalek danced around but never quite addressed.  Just check if you use the [pre-hashed variant](https://github.com/paritytech/substrate/issues/8055) anyplace.

**Comment by 0xdeafbeef** [comment]
We can publish https://github.com/broxus/ed25519-dalek
as `ed25519-dalek-ng` on crates.io and then transfer ownership to you.
Or we can transfer this repo to your organization

**Comment by burdges** [comment]
Again, I'd advise using ed25519-zebra instead of an e25519-dalek fork, assuming you use ed25519 anywhere you'd want batch verification.

**Comment by hdevalence** [comment]
@0xdeafbeef I'd advise just using `ed25519-zebra`; it has a minimal API, a single set of behavior, and an upstream (ZF) that's responsible for maintenance.  This experience burned me out on maintaining OSS for free, so I can't commit to doing it -- these libraries are maintained only on a best-effort basis.

**Comment by hdevalence** [comment]
I ended up needing an Ed25519 library for Penumbra, so I created https://github.com/penumbra-zone/ed25519-consensus , which has the minimal API from `ed25519-zebra` but uses this set of backing libraries.  I'll be maintaining it as needed going forward, but I don't expect there will be much development -- the functionality is basically complete, so hopefully there won't be much need to change things.
